service: cop-of-the-day-labmda

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  environment:
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    SLACK_CHANNEL: "#engineering"

functions:
  cron:
    handler: handler.run
    events:
      # 8 AM every weekday
      - schedule: cron(0 8 ? * MON-FRI *)
